directory-link-url
directory-link-category
directory-link-source
directory-link-thumbnail-image
post_title
post_type
post_status
post_author
post_id
directory-link-category
directory-link-resource-type
directory-link-resource-type
directory-link-type
directory-link-journal
directory-link-review-url
directory-link-review-source
directory-link-year
directory-link-month
directory-link-authors
directory-link-institution
directory-link-abstract
directory-link-full-text'])) {
directory-link-source
directory-link-description
directory-link-image-caption
post_title
directory-link-short-title
directory-link-venue
directory-link-venue
directory-link-start-date
directory-link-end-date
directory-link-city
directory-link-state
directory-link-country
directory-link-source-id-type
directory-link-source-id
directory-link-thumbnail-image
directory_link_category
local_path
remote_path
original_url
